name: Pre-release actions

on:
  push:
    branches: [ pre-release ]

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Pull baseline for HybridQ
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/hybridq-baseline:latest
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/hybridq-baseline:latest hybridq-baseline:latest

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build HybridQ container
        run: |
          docker-compose build --build-arg SKIP_PRE_CACHING=true --build-arg HYBRIDQ_DISABLE_CPP_CORE=true hybridq

      - name: Update documentation
        run: |
          docker run -v $(pwd)/docs:/opt/hybridq/docs --rm hybridq -c '\
            curl -L https://github.com/jgm/pandoc/releases/download/2.13/pandoc-2.13-linux-amd64.tar.gz | tar xvzf - -C /opt/ && \
            export PATH=/opt/pandoc-2.13/bin/:$PATH && \
            yum install -y texlive-latex-bin \
                           texlive-xetex-bin \
                           texlive-metafont-bin \
                           texlive-cm \
                           texlive-iftex \
                           texlive-ifluatex \
                           texlive-euenc \
                           texlive-zapfding \
                           texlive-polyglossia \
                           texlive-lm-math \
                           texlive-dvipdfmx && \
            pip install pdoc3==0.9.2 && \
            cd /opt/hybridq && \
            bash scripts/generate_documentation.sh'

      - name: Add documentation to repository
        run: |
          git config --global user.email "github@action"
          git config --global user.name "GitHub Action"
          git fetch -p
          git checkout pre-release
          git pull
          git add docs/*
          git commit -m "[Automated] Update documentation"
          git push -u origin pre-release

  linux_wheel:
    needs: documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create packages for Linux
        run: |
          bash scripts/generate_packages.sh

      - name: Add package to repository
        run: |
          git config --global user.email "github@action"
          git config --global user.name "GitHub Action"
          git fetch -p
          git checkout pre-release
          git pull
          git add packages/*.whl
          git commit -m "[Automated] Update wheels"
          git push -u origin pre-release

  macos_wheel:
    needs: linux_wheel
    runs-on: macos-10.15
    strategy:
      matrix:
        python-version: [ 3.7 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update PIP and install WHEEL
        run: |
          pip install -U wheel pip

      - name: Create package for MacOS
        run: |
          sed 's|from __future__ import annotations|from __future__ import annotations; from warnings import warn; warn("""The C++ simulator for this package has been compiled for a general x86-64 architecture without multi-threading support. For a better performance, try `pip install -U git+https://github.com/nasa/hybridq`.""")|' hybridq/circuit/simulation/simulation.py > __temp.py
          mv -f __temp.py hybridq/circuit/simulation/simulation.py
          CXX="clang++ -mmacosx-version-min=10.9" ARCH=x86-64 pip wheel . -v --no-dependencies -w packages/
          mv packages/hybridq-0.5.1-py3-none-any.whl packages/hybridq-$(python setup.py --version)-cp37-cp37m-macosx_10_9_x86_64.whl

      - name: Add package to repository
        run: |
          git fetch -p
          git checkout pre-release
          git pull
          git add packages/*.whl
          git commit -m "[Automated] Update wheels"
          git push -u origin pre-release
