name: Python Examples

on:
  push:
    branches: [ master, devel ]
  pull_request:
    branches: [ master, devel ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Pull baseline for HybridQ
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/hybridq-baseline:latest
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/hybridq-baseline:latest hybridq-baseline:latest

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build HybridQ container
        run: |
          docker-compose build --build-arg ARCH=x86-64 hybridq

      - name: Run example
        run: |
          docker run --rm hybridq -c 'cd /opt/hybridq && \
            python examples/example.py'

      - name: Run MPI example
        run: |
          docker run --rm hybridq -c 'cd /opt/hybridq && \
            mpiexec -n 2 --allow-run-as-root python examples/example-mpi.py && \
            mpiexec -n 2 --allow-run-as-root python examples/example-mpi-trace.py && \
            mpiexec -n 2 --allow-run-as-root python examples/example-mpi-clifford.py && \
            DISABLE_MPI_AUTODETECT=1 mpiexec -n 2 --allow-run-as-root python examples/example-mpi.py && \
            DISABLE_MPI_AUTODETECT=1 mpiexec -n 2 --allow-run-as-root python examples/example-mpi-trace.py && \
            DISABLE_MPI_AUTODETECT=1 mpiexec -n 2 --allow-run-as-root python examples/example-mpi-clifford.py'

      - name: Run simulator
        run: |
          docker run --rm hybridq -c 'cd /opt/hybridq && \
            hybridq examples/circuit.qasm /dev/null --verbose --optimize=evolution
            hybridq-dm examples/circuit_simple.qasm XIZXYZXZYZIXIZXXXZIZXIYY /dev/null --verbose --parallel'
