name: PyTest - simulation_2

on:
  push:
    branches: [ main, devel ]
  pull_request:
    branches: [ main, devel ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py: [cp37-cp37m, cp38-cp38, cp39-cp39]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build HybridQ container
        env:
          PYTHON_VERSION: ${{ matrix.py }}
        run: |
          docker-compose build --build-arg ARCH=x86-64 \
                               --build-arg BASELINE=docker.io/smandra/hybridq-baseline:$PYTHON_VERSION \
                               hybridq

      - name: Run tests
        run: |
          docker run --rm hybridq bash -c 'python -m pip install pytest-random-order && \
            python -m pytest -sv --random-order -k 'simulation_2__' /opt/hybridq/tests/tests.py'
