name: Python Check Format

on:
  push:
    branches: [ master, devel ]
  pull_request:
    branches: [ master, devel ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Pull baseline for HybridQ
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/hybridq-baseline:latest
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/hybridq-baseline:latest hybridq-baseline:latest

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build HybridQ container
        run: |
          docker-compose build --build-arg SKIP_PRE_CACHING=true --build-arg HYBRIDQ_DISABLE_CPP_CORE=true hybridq

      - name: Check format
        run: |
          docker run --rm hybridq -c 'pip install yapf==0.31.0 clang-format==9.0.0 && \
            cd /opt/hybridq && \
            bash scripts/check_format.sh'
